
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Laptop
 */
public class Menu extends javax.swing.JFrame {
    int id;
    String items[] = {"Peperoni Pizza  x", "Special Pizza  x", "Vegeterian Pizza  x", "Meat Hero Pizza   x", "Cola   x"};
    int quantity[] = {0, 0, 0, 0, 0};
    
    /**
     * Creates new form Menu
     */
    public Menu(int id) {
        initComponents();
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        icon_up_left = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        profile_jlabel = new javax.swing.JLabel();
        icon_profile = new javax.swing.JLabel();
        food_jlabel = new javax.swing.JLabel();
        cart_jlabel = new javax.swing.JLabel();
        icon_cart = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        food_jpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        add_pepperoni = new javax.swing.JButton();
        add_special = new javax.swing.JButton();
        add_vegeterian = new javax.swing.JButton();
        add_meat = new javax.swing.JButton();
        add_cola = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cart_jpanel = new javax.swing.JPanel();
        order_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cart_textarea = new javax.swing.JTextArea();
        clear_cart_button = new javax.swing.JButton();
        error_cart_items_label = new javax.swing.JLabel();
        profile_jpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtextfield_street = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtextfield_zip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtextfield_town = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtextfield_number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtextfield_floor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtextfield_phone = new javax.swing.JTextField();
        save_profile_button = new javax.swing.JButton();
        error_jlabel = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(92, 103));

        icon_up_left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/papasIcon.png"))); // NOI18N
        icon_up_left.setText(" ");
        icon_up_left.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        logoutbutton.setBorder(null);
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        profile_jlabel.setBackground(new java.awt.Color(255, 255, 255));
        profile_jlabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        profile_jlabel.setForeground(new java.awt.Color(255, 255, 204));
        profile_jlabel.setText("Profile");
        profile_jlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_jlabelMouseClicked(evt);
            }
        });

        icon_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N
        icon_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_profileMouseClicked(evt);
            }
        });

        food_jlabel.setBackground(new java.awt.Color(255, 255, 255));
        food_jlabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        food_jlabel.setForeground(new java.awt.Color(255, 255, 204));
        food_jlabel.setText("Food");
        food_jlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                food_jlabelMouseClicked(evt);
            }
        });

        cart_jlabel.setBackground(new java.awt.Color(255, 255, 255));
        cart_jlabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cart_jlabel.setForeground(new java.awt.Color(255, 255, 204));
        cart_jlabel.setText("Cart");
        cart_jlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_jlabelMouseClicked(evt);
            }
        });

        icon_cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart.png"))); // NOI18N
        icon_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_cartMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/food.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(icon_up_left, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(food_jlabel)
                    .addComponent(jLabel1))
                .addGap(231, 231, 231)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cart_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(icon_cart)
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_jlabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(icon_profile)
                        .addGap(16, 16, 16)))
                .addGap(71, 71, 71)
                .addComponent(logoutbutton)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(icon_up_left))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon_cart, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icon_profile, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(logoutbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(food_jlabel)
                    .addComponent(cart_jlabel)
                    .addComponent(profile_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));

        food_jpanel.setBackground(new java.awt.Color(255, 153, 0));

        jScrollPane2.setToolTipText("");
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Pepperoni.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Special.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Vegeterian.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Meat_hero.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pepsi.png"))); // NOI18N

        add_pepperoni.setBackground(new java.awt.Color(102, 153, 0));
        add_pepperoni.setText("Add to Cart");
        add_pepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pepperoniActionPerformed(evt);
            }
        });

        add_special.setBackground(new java.awt.Color(102, 153, 0));
        add_special.setText("Add to Cart");
        add_special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_specialActionPerformed(evt);
            }
        });

        add_vegeterian.setBackground(new java.awt.Color(102, 153, 0));
        add_vegeterian.setText("Add to Cart");
        add_vegeterian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_vegeterianActionPerformed(evt);
            }
        });

        add_meat.setBackground(new java.awt.Color(102, 153, 0));
        add_meat.setText("Add to Cart");
        add_meat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_meatActionPerformed(evt);
            }
        });

        add_cola.setBackground(new java.awt.Color(102, 153, 0));
        add_cola.setText("Add to Cart");
        add_cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_colaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 204));
        jLabel14.setText("Cola");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 204));
        jLabel15.setText("Pepperoni Pizza");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 204));
        jLabel16.setText("Special Pizza");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 204));
        jLabel17.setText("Vegeterian Pizza");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 204));
        jLabel18.setText("Meat Hero Pizza");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_meat)
                    .addComponent(add_pepperoni)
                    .addComponent(add_special)
                    .addComponent(add_vegeterian)
                    .addComponent(add_cola))
                .addGap(73, 73, 73))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_pepperoni)
                        .addComponent(jLabel15)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_special)
                        .addComponent(jLabel16)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_vegeterian)
                        .addComponent(jLabel17)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_meat)
                        .addComponent(jLabel18)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_cola)
                        .addComponent(jLabel14)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout food_jpanelLayout = new javax.swing.GroupLayout(food_jpanel);
        food_jpanel.setLayout(food_jpanelLayout);
        food_jpanelLayout.setHorizontalGroup(
            food_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(food_jpanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        food_jpanelLayout.setVerticalGroup(
            food_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(food_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", food_jpanel);

        cart_jpanel.setBackground(new java.awt.Color(255, 153, 0));

        order_button.setBackground(new java.awt.Color(102, 153, 0));
        order_button.setText("Order Now");
        order_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_buttonActionPerformed(evt);
            }
        });

        cart_textarea.setEditable(false);
        cart_textarea.setBackground(new java.awt.Color(255, 153, 0));
        cart_textarea.setColumns(20);
        cart_textarea.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cart_textarea.setForeground(new java.awt.Color(255, 255, 204));
        cart_textarea.setRows(5);
        cart_textarea.setBorder(null);
        cart_textarea.setFocusable(false);
        jScrollPane1.setViewportView(cart_textarea);

        clear_cart_button.setBackground(new java.awt.Color(102, 153, 0));
        clear_cart_button.setText("Clear Cart");
        clear_cart_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_cart_buttonActionPerformed(evt);
            }
        });

        error_cart_items_label.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        error_cart_items_label.setForeground(new java.awt.Color(255, 255, 204));
        error_cart_items_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cart_jpanelLayout = new javax.swing.GroupLayout(cart_jpanel);
        cart_jpanel.setLayout(cart_jpanelLayout);
        cart_jpanelLayout.setHorizontalGroup(
            cart_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cart_jpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(cart_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cart_jpanelLayout.createSequentialGroup()
                        .addGroup(cart_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clear_cart_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(order_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(cart_jpanelLayout.createSequentialGroup()
                        .addComponent(error_cart_items_label, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        cart_jpanelLayout.setVerticalGroup(
            cart_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cart_jpanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(error_cart_items_label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(cart_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order_button)
                    .addComponent(clear_cart_button))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("tab2", cart_jpanel);

        profile_jpanel.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Street");

        jtextfield_street.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Number");

        jtextfield_zip.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Town");

        jtextfield_town.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Zip Code");

        jtextfield_number.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Floor");

        jtextfield_floor.setBackground(new java.awt.Color(255, 255, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("Phone no.");

        jtextfield_phone.setBackground(new java.awt.Color(255, 255, 204));

        save_profile_button.setBackground(new java.awt.Color(102, 153, 0));
        save_profile_button.setText("Save");
        save_profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_profile_buttonActionPerformed(evt);
            }
        });

        error_jlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout profile_jpanelLayout = new javax.swing.GroupLayout(profile_jpanel);
        profile_jpanel.setLayout(profile_jpanelLayout);
        profile_jpanelLayout.setHorizontalGroup(
            profile_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_jpanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(profile_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(save_profile_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(profile_jpanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtextfield_street, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtextfield_number, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profile_jpanelLayout.createSequentialGroup()
                        .addGroup(profile_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(profile_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_jpanelLayout.createSequentialGroup()
                                .addComponent(jtextfield_floor)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jtextfield_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profile_jpanelLayout.createSequentialGroup()
                                .addComponent(jtextfield_town, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jtextfield_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(error_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        profile_jpanelLayout.setVerticalGroup(
            profile_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_jpanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(profile_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jtextfield_street, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtextfield_number, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profile_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtextfield_town, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtextfield_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profile_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtextfield_floor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtextfield_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(error_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(save_profile_button)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", profile_jpanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, -1, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void profile_jlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_jlabelMouseClicked
        // TODO add your handling code here:
        error_jlabel.setText("");
        setprofilefields(id);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_profile_jlabelMouseClicked

    private void food_jlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_food_jlabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_food_jlabelMouseClicked

    private void cart_jlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_jlabelMouseClicked
        // TODO add your handling code here:
        setquantity();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_cart_jlabelMouseClicked

    private void save_profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_profile_buttonActionPerformed
        // TODO add your handling code here:
        
        //get text field info 
        error_jlabel.setText("");
        
        String street = jtextfield_street.getText();
        String number =jtextfield_number.getText();
        String town = jtextfield_town.getText();
        String zip = jtextfield_zip.getText();
        String floor =jtextfield_floor.getText();
        String phone = jtextfield_phone.getText();
        
        if(street.isEmpty() || number.isEmpty() || town.isEmpty() || zip.isEmpty()|| floor.isEmpty() || phone.isEmpty()){
            error_jlabel.setText("Fields cannot be empty");
        }else{
            updateprofile(street, number, town, zip, floor, phone);
        
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_save_profile_buttonActionPerformed

    private void icon_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_profileMouseClicked
        // TODO add your handling code here:
        error_jlabel.setText("");
        setprofilefields(id);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_icon_profileMouseClicked

    private void icon_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_cartMouseClicked
        // TODO add your handling code here:
        setquantity();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_icon_cartMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void order_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_buttonActionPerformed
        // TODO add your handling code here:
        
        //System.out.println(quantity[0] +" "+ quantity[1] +" "+ quantity[2] +" "+ quantity[3] +" "+ quantity[4]);
        
        if(quantity[0] == 0 && quantity[1] == 0 && quantity[2] == 0 && quantity[3] == 0 && quantity[4] == 0){
            error_cart_items_label.setText("Your Cart is Empty");
        }else{
            ordernow();
        
            quantity[0] = 0;
            quantity[1] = 0;
            quantity[2] = 0;
            quantity[3] = 0;
            quantity[4] = 0;
        
            error_cart_items_label.setText("");
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_order_buttonActionPerformed

    private void add_pepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pepperoniActionPerformed
        // TODO add your handling code here:
        quantity[0]++;
    }//GEN-LAST:event_add_pepperoniActionPerformed

    private void add_specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_specialActionPerformed
        // TODO add your handling code here:
        quantity[1]++;
    }//GEN-LAST:event_add_specialActionPerformed

    private void add_vegeterianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_vegeterianActionPerformed
        // TODO add your handling code here:
        quantity[2]++;
    }//GEN-LAST:event_add_vegeterianActionPerformed

    private void add_meatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_meatActionPerformed
        // TODO add your handling code here:
        quantity[3]++;
    }//GEN-LAST:event_add_meatActionPerformed

    private void add_colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_colaActionPerformed
        // TODO add your handling code here:
        quantity[4]++;
    }//GEN-LAST:event_add_colaActionPerformed

    private void clear_cart_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_cart_buttonActionPerformed
        // TODO add your handling code here:
        quantity[0] = 0;
        quantity[1] = 0;
        quantity[2] = 0;
        quantity[3] = 0;
        quantity[4] = 0;
        
        setquantity();
    }//GEN-LAST:event_clear_cart_buttonActionPerformed

    private void updateprofile(String street, String number, String town, String zip, String floor, String phone){
        Connection conn = DatabaseConn.connectDB();
        
        if(conn != null){
           
            try {
                
                PreparedStatement st = (PreparedStatement) conn.prepareStatement("UPDATE profile SET street = ? , number = ? , town = ? , zip = ? , floor = ? , phone = ? WHERE id = ?"); //fill table customer
                
                st.setString(1, street);
                st.setInt(2, Integer.parseInt(number));
                st.setString(3,town);
                st.setInt(4,Integer.parseInt(zip));
                st.setInt(5,Integer.parseInt(floor));
                st.setString(6,phone);
                st.setInt(7,id);
                
                st.executeUpdate();
            
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.out.println("Connection not available");
        }
    }
    
    private void setprofilefields(int id){
        
        Connection conn = DatabaseConn.connectDB();
        
        if(conn != null){
           
            try {
                
                PreparedStatement st = (PreparedStatement) conn.prepareStatement("Select * from profile where id = ?");
                st.setInt(1, id); //set first ? with the id
                
                ResultSet res = st.executeQuery();
                
                if (res.next()){ //if there is an id match set jetextfields with these values
                    if (res.getString("street") != null){
                        jtextfield_street.setText(res.getString("street"));
                        jtextfield_number.setText(String.valueOf(res.getInt("number")));
                        jtextfield_town.setText(res.getString("town"));
                        jtextfield_zip.setText(String.valueOf(res.getInt("zip")));
                        jtextfield_floor.setText(String.valueOf(res.getInt("floor")));
                        jtextfield_phone.setText(res.getString("phone"));
                    }
                    
                }
            
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.out.println("Connection not available");
        }      
    }
    
    private void setquantity(){
        error_cart_items_label.setText("");
        
        String temp = "";
        
        for(int i =0; i<5; i++){
            if(quantity[i] > 0){
                temp += "\n" + items[i] + String.valueOf(quantity[i] + "\n");
            }
        }
        
        cart_textarea.setText(temp);
    }
    
    private void ordernow(){
        
        Connection conn = DatabaseConn.connectDB();
        PreparedStatement st = null;
        ResultSet res = null;
        
        if(conn != null){
           
            try {
                st = (PreparedStatement) conn.prepareStatement("INSERT INTO order_queue VALUES (NULL,?,?,?,?,?)"); //fill table customer
                
                st.setInt(1, quantity[0]);
                st.setInt(2, quantity[1]);
                st.setInt(3,quantity[2]);
                st.setInt(4,quantity[3]);
                st.setInt(5,quantity[4]);
                
                int resu = st.executeUpdate();
            
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.out.println("Connection not available");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_cola;
    private javax.swing.JButton add_meat;
    private javax.swing.JButton add_pepperoni;
    private javax.swing.JButton add_special;
    private javax.swing.JButton add_vegeterian;
    private javax.swing.JLabel cart_jlabel;
    private javax.swing.JPanel cart_jpanel;
    private javax.swing.JTextArea cart_textarea;
    private javax.swing.JButton clear_cart_button;
    private javax.swing.JLabel error_cart_items_label;
    private javax.swing.JLabel error_jlabel;
    private javax.swing.JLabel food_jlabel;
    private javax.swing.JPanel food_jpanel;
    private javax.swing.JLabel icon_cart;
    private javax.swing.JLabel icon_profile;
    private javax.swing.JLabel icon_up_left;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtextfield_floor;
    private javax.swing.JTextField jtextfield_number;
    private javax.swing.JTextField jtextfield_phone;
    private javax.swing.JTextField jtextfield_street;
    private javax.swing.JTextField jtextfield_town;
    private javax.swing.JTextField jtextfield_zip;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton order_button;
    private javax.swing.JLabel profile_jlabel;
    private javax.swing.JPanel profile_jpanel;
    private javax.swing.JButton save_profile_button;
    // End of variables declaration//GEN-END:variables
}
